config/routes.rb
Speedrunner::Application.routes.draw do

  root to: "games#index"

  resources :users, except: :new do
    member do
      get 'moderate'
      post 'moderateset'
    end
    resources :follows, only: [:create, :destroy]
  end

  resources :games do
    resources :runs do
      member do
        get 'verifyrun'
      end
      resources :comments, only: [:create, :destroy]
    end
  end

  match '/signup',  to: 'users#new'
  match '/signin',   to: "sessions#new", via: :get
  match '/signin',   to: "sessions#create", via: :post, as: :post_sessions
  match '/signout', to: 'sessions#destroy'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :text
  belongs_to :run
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.json

  # GET /comments/new
  # GET /comments/new.json
  def new
    @game = Game.find(params[:game_id])
    @run = Run.find(params[:run_id])

    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # POST /comments
  # POST /comments.json
  def create
    @game = Game.find(params[:game_id])
    @run = Run.find(params[:run_id])
    @comment = @run.comments.create(params[:comment])
    @comment.run = @run
    @comment.user = current_user
    respond_to do |format|
      if @comment.save
        format.html { redirect_to game_run_path(@game, @run), notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.haml
= form_for([:game, :run, @comment]) do |f|
  - if @comment.errors.any?
    #error_explanation
      %h2= pluralize(@comment.errors.count, "error")
      prohibited this comment from being saved:

      %ul
      - @comment.errors.full_messages.each do |msg|
        %li= msg

  .field
    = f.label :text
    = f.text_area :text, cols: 25, rows: 5
    
  .actions
    =f.submit

app/views/comments/edit.html.haml
%h1
  Editing comment

= render 'form'

= link_to 'Show', @comment
%br
= link_to 'Back', comments_path

app/views/comments/index.html.haml
%h1
  Listing comments

%table
  %tr
    %th Text
    %th
    %th
    %th

- @comments.each do |comment|
  %tr
    %td= comment.text
    %td= link_to 'Show', comment
    %td= link_to 'Edit', edit_comment_path(comment)
    %td= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Comment', new_comment_path

app/views/comments/new.html.haml
%h1
  New comment

= render 'form'

= link_to 'Back', game_run_comments_path(@game, @run)

app/views/comments/show.html.haml
%p#notice= notice

%p
  %b
    Text:
  = @comment.text


= link_to 'Edit', edit_comment_path(@comment)
%br
= link_to 'Back', comments_path