config/routes.rb
Speedrunner::Application.routes.draw do

  root to: "games#index"

  resources :users, except: :new do
    member do
      get 'moderate'
      post 'moderateset'
    end
    resources :follows, only: [:create, :destroy]
  end

  resources :games do
    resources :runs do
      member do
        get 'verifyrun'
      end
      resources :comments, only: [:create, :destroy]
    end
  end

  match '/signup',  to: 'users#new'
  match '/signin',   to: "sessions#new", via: :get
  match '/signin',   to: "sessions#create", via: :post, as: :post_sessions
  match '/signout', to: 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :moderates, :dependent => :destroy
  has_many :follows, :dependent => :destroy
  has_many :runs, :dependent => :destroy
  has_many :comments, :dependent => :destroy

  attr_accessible :email, :first_name, :last_name, :password, :password_confirmation, :username, :avatar
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  has_secure_password

  validates(:first_name, presence: true)
  validates(:last_name, presence: true)
  validates(:email, presence: true, format: { with: /@.+\.[a-z]+/i }, uniqueness: { case_sensitive: false })
  validates(:username, presence: true, length: { minimum: 3 }, uniqueness: { case_sensitive: false })
  validates(:password, presence: true, length: { minimum: 3 }, confirmation: true)
  validates(:password_confirmation, presence: true)

  before_validation(on: :create) do |user|
    if user.username =~ /@/i
      user.username = user.username.sub(/@/, "")
    end
    user.username = user.username.downcase
    user.email = user.email.downcase
    create_remember_token
  end

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :admin_user, only: [:index]
  before_filter :correct_user, only: [:edit, :update]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @runs = @user.runs.all
    if signed_in?
      @following = Follow.where("followee_id = ? AND user_id = ?", params[:id], current_user.id)
    end
    @followings = Follow.where("user_id = ?", params[:id])
    @usersbeingfollowed = []
    @followings.each do |f|
      @usersbeingfollowed << User.find(f.followee_id)
    end
  end

  def moderate
    @user = User.find(params[:id])
    @games = Game.all.collect { |g| [g.name, g.id] }
    @moderator = []
  end

  def moderateset
    @users = User.all
    @user = User.find(params[:user_id])
    @game = Game.find(params[:game_id])
    if @user.moderates.where(game_id: @game.id).empty?
      @user.moderates << Moderate.new(user_id: @user.id, game_id: @game.id)
      redirect_to users_path
    else
      render 'index', notice: "#{@user.username} already moderates that game"
    end
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      redirect_to @user, notice: "Welcome to SpeedRunner #{@user.first_name}"
    else
      render 'new', notice: "Something went wrong"
    end
  end

  def update
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
  end

  private

    def correct_user
      if !current_user.nil?
        @user = User.find(params[:id])
        if @user.id != current_user.id
          redirect_to root_path unless current_user.admin?
        end
      else
        redirect_to games_path
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for(@user) do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= pluralize(@user.errors.count, "Error") 
      prohibited this user from being saved:

      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :username
    = f.text_field :username 
  
  .field
    = f.label :first_name
    = f.text_field :first_name 
  
  .field
    = f.label :last_name
    = f.text_field :last_name 
  
  .field
    = f.label :email
    = f.text_field :email 
  
  .field
    = f.label :password
    = f.password_field :password

  .field
    = f.label :password_confirmation
    = f.password_field :password_confirmation

  .field
    = f.label :avatar
    = f.file_field :avatar

  %br
  
  .actions
    = f.submit 

app/views/users/edit.html.haml
%h1
  Editing user

= render 'form'

= link_to 'Show', @user
%br
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1
  Listing users


%table.table
  %thead
    %tr
      %th Username
      %th First name
      %th Last name
      %th Email
      %th
      %th
      %th

  - @users.each do |user|
    %tbody
      %tr
        %td= user.username
        %td= user.first_name
        %td= user.last_name
        %td= user.email
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }
        %td= link_to 'Make Moderator', moderate_user_path(user), class: "btn"
%br

= link_to 'New User', signup_path

app/views/users/moderate.html.haml
%h1
  = "Make #{@user.username} Moderator"
%br

- if !@user.moderates.empty?
  %h2
    = "#{@user.username} already moderates these games:"
    .well
      %ul
        - @user.moderates.each do |mod|
          %li= Game.find(mod.game_id).name

%br

= form_for("moderator[]", url: { action: "moderateset", user_id: params[:id] }) do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= pluralize(@user.errors.count, "Error")
      prohibited this user from being saved:

      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label "For which game?"
    = select_tag(:game_id, options_for_select(@games))
  .actions
    = f.submit "Submit"

app/views/users/new.html.haml
%h1
  New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
.row
  .span4
    %p
      %b
      = image_tag @user.avatar.url(:thumb)
    %p
      %b
        Username:
      = @user.username

    %p
      %b
        First name:
      = @user.first_name

    %p
      %b
        Last name:
      = @user.last_name

    %p
      %b
        Email:
      = @user.email

  .span8
    .offset5
      %p
        %b
          People #{@user.username} is Following:
          %br
        -@usersbeingfollowed.each do |u|
          = image_tag u.avatar.url(:thumb)
          = link_to u.username, user_path(u.id)
          %br

%br

%h1= "#{@user.username}'s runs"
.row
  .span8
    %table.table
      %thead
        %tr
          %th
            Time
          %th
            Game Name
          %th
            Verified
      %tbody
        - @runs.each do |run|
          %tr
            %td
              = link_to run.time_in_seconds, game_run_path(run.game, run)
            %td
              = link_to run.game.name, game_path(run.game)
            %td
              - if run.verified
                √ 

-if signed_in?
  -if @user != current_user
    -if @following.empty?
      =form_tag(user_follows_path(@user), :method => :create) do
        .actions
          =submit_tag("Follow")
    -else
      =link_to 'Unfollow', user_follow_path(@user), method: :delete

= link_to 'Back', users_path