config/routes.rb
Speedrunner::Application.routes.draw do

  root to: "games#index"

  resources :users, except: :new do
    member do
      get 'moderate'
      post 'moderateset'
    end
    resources :follows, only: [:create, :destroy]
  end

  resources :games do
    resources :runs do
      member do
        get 'verifyrun'
      end
      resources :comments, only: [:create, :destroy]
    end
  end

  match '/signup',  to: 'users#new'
  match '/signin',   to: "sessions#new", via: :get
  match '/signin',   to: "sessions#create", via: :post, as: :post_sessions
  match '/signout', to: 'sessions#destroy'

end

app/models/game.rb
class Game < ActiveRecord::Base
  attr_accessible :name, :publisher, :release_year, :series, :system, :coverart
  has_attached_file :coverart, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  has_many :runs, :dependent => :destroy
  has_many :moderates, :dependent => :destroy
  has_many :users, :through => :moderates

  validates(:name, presence: true)
  validates(:publisher, presence: true)
  validates(:release_year, numericality: { only_integer: true, less_than_or_equal_to: Time.now.year } )
  validates(:system, presence: true)
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_filter :authenticate, only: [:edit, :update]
  
  def index
    @games = Game.all

    respond_to do |format|
      format.html
      format.json { render json: @games }
    end
  end

  def show
    @game = Game.find(params[:id])
    @runsany = @game.runs.where(category: "any%")
    if !@runsany.empty? && @runsany.first.url =~ /youtube/
      @firstanyurl = @runsany.first.url.split("=").last
    end
    @runs100 = @game.runs.where(category: "100%")
    if !@runs100.empty? && @runs100.first.url =~ /youtube/
      @first100url = @runs100.first.url.split("=").last
    end
    if current_user
      @mod = @game.moderates.where(user_id: current_user.id).first
    end

    respond_to do |format|
      format.html
      format.json { render json: @game }
    end
  end

  def new
    @game = Game.new

    respond_to do |format|
      format.html
      format.json { render json: @game }
    end
  end

  def edit
    @game = Game.find(params[:id])
  end

  def create
    @game = Game.new(params[:game])

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.haml
= form_for(@game) do |f|

  - if @game.errors.any?
    #error_explanation
      %div{:class => "alert alert-error"}
        %a.close{"data-dismiss" => "alert"} ×
        %h2= pluralize(@game.errors.count, "error")
        prohibited this game from being saved:
        %ul
          - @game.errors.full_messages.each do |msg|
            %li= msg

  .field
    = f.label :name
    = f.text_field :name, required: true

  .field
    = f.label :system
    = f.text_field :system, required: true
    
  .field
    = f.label :release_year
    = f.number_field :release_year, value: 2000, required: true

  .field
    = f.label :publisher
    = f.text_field :publisher, required: true

  .field
    = f.label :series
    = f.text_field :series, required: true

  .field
    = f.label :coverart, "Cover art:"
    = f.file_field :coverart

  .actions
    = f.submit

app/views/games/edit.html.haml
%h1
  Editing game

= render 'form'

= link_to 'Show', @game
%br
= link_to 'Back', games_path

app/views/games/index.html.haml
%h1
  Listing games

%table.table
  %thead
    %tr
      %th Name
      %th System
      %th Release year
      %th Publisher
      %th Series
      - if current_user && is_admin?
        %th
        %th
  %tbody
    - @games.each do |game|
      %tr
        %td= link_to game.name, game
        %td= game.system
        %td= game.release_year
        %td= game.publisher
        %td= game.series
        - if current_user && is_admin?
          %td= link_to 'Edit', edit_game_path(game), class: "btn"
          %td= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn"

%br
- if !current_user
  = link_to "Sign Up", signup_path, class: "btn btn-large btn-primary"

- if current_user && is_admin?
  = link_to 'New Game', new_game_path, class: "btn"

app/views/games/new.html.haml
%h1
  New game

= render 'form'

= link_to 'Back', games_path

app/views/games/show.html.haml
%h1
  = image_tag @game.coverart.url(:thumb) 
  = @game.name

.well
  %p
    %b
      System:
    = @game.system

  %p
    %b
      Release year:
    = @game.release_year

  %p
    %b
      Publisher:
    = @game.publisher

  %p
    %b
      Series:
    = @game.series

- if !@firstanyurl.nil? || !@first100url.nil?
  .row
    .span6
      - if !@firstanyurl.nil?
        %iframe{ width: "420", height: "315", src: "http://www.youtube.com/embed/#{@firstanyurl}", frameborder: "0", allowfullscreen: true }
    .span6 
      - if !@first100url.nil?
        %iframe{ width: "420", height: "315", src: "http://www.youtube.com/embed/#{@first100url}", frameborder: "0", allowfullscreen: true }

%br
- if current_user
  = link_to "New Run", new_game_run_path(@game), class: "btn"
%br
%br
.row
  .span6
    %h1
      Runs - Any%
    %table.table.table-striped
      %thead
        %tr
          %th
            Username
          %th
            Time
          %th
            Category
          %th
            Link
          %th
            Verified
          - if !@mod.nil? || is_admin?
            %th
              Verify?
      %tbody
        - @runsany.each do |run|
          - if run.verified == true || !@mod.nil? || is_admin?
            %tr
              %td
                = link_to "#{run.user.username}", run.user
              %td
                = link_to "#{run.time_in_seconds}", game_run_path(@game, run)
              %td
                = run.category
              %td
                = link_to "Video", run.url, target: "_blank"
              %td
                - if run.verified
                  √
              - if !@mod.nil? || is_admin?
                %td
                  - if run.verified
                    = link_to "Remove Verification", verifyrun_game_run_path(@game, run), class: "btn"
                  - else
                    = link_to "Verify Run", verifyrun_game_run_path(@game, run), class: "btn"



  .span6
    %h1
      Runs - 100%
    %table.table.table-striped.span6
      %thead
        %tr
          %th
            Username
          %th
            Time
          %th
            Category
          %th
            Link
          %th
            Verified
          - if !@mod.nil? || is_admin?
            %th
              Verify?
      %tbody
        - @runs100.each do |run|
          - if run.verified == true || !@mod.nil? || is_admin?
            %tr
              %td
                = link_to "#{run.user.username}", run.user
              %td
                = link_to "#{run.time_in_seconds}", game_run_path(@game, run)
              %td
                = run.category
              %td
                = run.url
              %td
                - if run.verified
                  √
              - if !@mod.nil? || is_admin?
                %td
                  - if run.verified
                    = link_to "Remove Verification", verifyrun_game_run_path(@game, run), class: "btn"
                  - else
                    = link_to "Verify Run", verifyrun_game_run_path(@game, run), class: "btn"

%br
= link_to 'Back', games_path, class: "btn"

- if current_user && is_admin?
  %br
  %br
  = link_to 'Edit Game', edit_game_path(@game), class: "btn"
  %br