config/routes.rb
Speedrunner::Application.routes.draw do

  root to: "games#index"

  resources :users, except: :new do
    member do
      get 'moderate'
      post 'moderateset'
    end
    resources :follows, only: [:create, :destroy]
  end

  resources :games do
    resources :runs do
      member do
        get 'verifyrun'
      end
      resources :comments, only: [:create, :destroy]
    end
  end

  match '/signup',  to: 'users#new'
  match '/signin',   to: "sessions#new", via: :get
  match '/signin',   to: "sessions#create", via: :post, as: :post_sessions
  match '/signout', to: 'sessions#destroy'

end

app/models/run.rb
class Run < ActiveRecord::Base
  attr_accessible :category, :time_in_seconds, :url
  belongs_to :game
  belongs_to :user
  has_many :comments, :dependent => :destroy

  default_scope order("time_in_seconds ASC")
  
  validates(:time_in_seconds, presence: true, format: { with: /[0-9]{2}:[0-5][0-9]:[0-5][0-9]/ })
  validates(:category, presence: true)
  validates(:url, presence: true)

  before_save do |run|
    if run.url !~ /^(http:\/\/|https:\/\/).*\.com/
      run.url = "http://#{run.url}"
    end
  end

  def self.togglerun(runid)
    run = Run.find(runid)
    run.toggle!(:verified)
  end
end

app/controllers/runs_controller.rb
class RunsController < ApplicationController
  before_filter :moderator, only: [:verifyrun]
  def index
    @runs = Run.all

    respond_to do |format|
      format.html
      format.json { render json: @runs }
    end
  end

  def show
    @run = Run.find(params[:id])
    @game = @run.game
    @comments = Comment.where("run_id=?", @run.id)
    @comment = Comment.new()
    if @run.url =~ /youtube/
      @youtube = true
      @suburl = @run.url.split("=").last
    else
      @youtube = false
    end

    respond_to do |format|
      format.html
      format.json { render json: @run }
    end
  end

  def new
    @game = Game.find(params[:game_id])
    @run = Run.new

    respond_to do |format|
      format.html
      format.json { render json: @run }
    end
  end

  def edit
    @run = Run.find(params[:id])
  end

  def create
    @game = Game.find(params[:game_id])
    @run = @game.runs.create(params[:run])
    @run.user = current_user
    if @run.url =~ /.+\..+/
      @run.verified = true
    else
      @run.verified = false
    end

    if @run.save
      redirect_to game_path(@game), notice: 'Run was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @game = Game.find(params[:game_id])
    @run = Run.find(params[:id])

    respond_to do |format|
      if @run.update_attributes(params[:run])
        @run.user = current_user
        @run.save
        format.html { redirect_to game_path(@game), notice: 'Run was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @run.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @run = Run.find(params[:id])
    @run.destroy

    respond_to do |format|
      format.html { redirect_to runs_url }
      format.json { head :no_content }
    end
  end

  def verifyrun
    if Run.togglerun(params[:id])
      redirect_to game_path(Game.find(params[:game_id])), notice: "Run verification toggled"
    else
      redirect_to game_path(Game.find(params[:game_id])), notice: "Could not toggle verification"
    end
  end
end

app/helpers/runs_helper.rb
module RunsHelper
end

app/views/runs/_form.html.haml
= form_for([:game, @run]) do |f|
  - if @run.errors.any?
    #error_explanation
      %h2= pluralize(@run.errors.count, "error")
      prohibited this run from being saved:

      %ul
      - @run.errors.full_messages.each do |msg|
        %li= msg
        

  .field
    = f.label :url
    = f.text_field :url, required: true
  .field
    = f.label :category
    = f.select :category, "<option>any%</option><option>100%</option>".html_safe
  .field
    = f.label :time_in_seconds, "Time eg: HH:MM:SS"
    = f.text_field :time_in_seconds

  .actions
    = f.submit

app/views/runs/edit.html.haml
%h1
  Editing run

= render 'form'

= link_to 'Show', @run
%br
= link_to 'Back', runs_path

app/views/runs/index.html.haml
%h1
  Listing runs

%table.table
  %tr
    %th Url
    %th Verified
    %th Category
    %th Time in seconds
    %th
    %th
    %th

  - @runs.each do |run|
    %tr
      %td= run.url
      %td= run.verified
      %td= run.category
      %td= run.time_in_seconds
      %td= link_to 'Show', game_run_path(run.game_id, run)
      %td= link_to 'Edit', '#'
      %td= link_to 'Destroy', '#', method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Run', '#'

app/views/runs/new.html.haml
%h1
  New run

= render 'form'

= link_to 'Back', game_runs_path(@game)

app/views/runs/show.html.haml
%p#notice= notice

%p
  %b
    Url:
  = link_to @run.url, @run.url, target: "_blank"

%p
  %b
    Verified:
  = @run.verified

%p
  %b
    Category:
  = @run.category

%p
  %b
    Time in seconds:
  = @run.time_in_seconds

- if @youtube == true
  %iframe{ width: "420", height: "315", src: "http://www.youtube.com/embed/#{@suburl}", frameborder: "0", allowfullscreen: true }

#comment
  %p
    %b
      Comments:
      %br
    -@comments.each do |c|
      .well
        %p
          %b
            .pull-left= "#{c.user.username}:"
        .pull-right= c.created_at
        %br
        %br
        = c.text
        %br

-if signed_in?
  =form_tag(game_run_comments_path(@run.game, @run), :method => :create) do
    .field
      =label :comment, :text, ("Comment")
      =text_area :comment, :text, cols: 25, rows: 5

    .actions
      =submit_tag("Add")

%br
- if current_user
  - if @run.user == current_user || is_admin?
    = link_to 'Edit', edit_game_run_path(@run), class: "btn"
= link_to 'Back', game_path(@game), class: "btn"


%br
%br